name = "Vanilla++"
author = "Ygor (toastedwaffles)"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95fb34dc5eb12bb0734c3e37dd890d42d0d372c77d7468b8960eef2e48a9fdbc"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
