name = "Vanilla++"
author = "Ygor (toastedwaffles)"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cce843eb6e1784188ee726bc39d75a2b0e360dbf129b6476c32449943843a15"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
