name = "Vanilla++"
author = "Ygor (toastedwaffles)"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04823bb6d5cb324a533369c05b9cdf42652c1d23e3ac7b51c5b7f6addb89c400"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
