name = "Vanilla++"
author = "Ygor (toastedwaffles)"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "055beb7f443c5d2f7971499c0fb09f1b596dba22ddd8d716b2afd73f0c382c5c"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
