name = "Vanilla++ Fabric 1.19.2"
author = "ygoroffici"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bad8890175d0e27d9af6c3b90748e09ebedfa27519acdff97bbab07e7ec1036"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
