name = "Vanilla++"
author = "Ygor (toastedwaffles)"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "545c5b9dcef7e4daf8b9691e334f7ee458e16b381e962a645a55e721b19aa3d8"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
