name = "Vanilla++ Fabric 1.20.1"
author = "ygoroffici"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd72e129b7ab3c856a9ccb06837fb4e71dbcb34491b3a3ed5b48b27e67598ce2"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
