name = "Vanilla++"
author = "Ygor (toastedwaffles)"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bd281623a337b6f26bf45843c972196184e21eaa2e486b32692f6a46500e9d0"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
