name = "Vanilla++"
author = "Ygor (toastedwaffles)"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c41e5407805b75d4904db7366c40bf68d9b722437f0713ea7507daec1630c9e"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
