name = "Vanilla++"
author = "Ygor (toastedwaffles)"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaef5f00b37b168d97cabef07a1b8dee3dd984d026c947e06b72a2943b762a19"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
