name = "Vanilla++ Fabric 1.20.1"
author = "ygoroffici"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6269b2071ecd47845f1196b46c2a93a6f52ec22464d4ba1542df89edb611238"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
