triggerAtDistanceBelow = 32
damageOnFall = 19
fallingHeight = 300
preventDeath = false
triggerInOverworld = true
triggerInNether = true
triggerInEnd = true
disableVanillaAntiCheatWhileFalling = true
dimensionAllowList = []
dimensionDenyList = []
